[package]
name = "athena"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "athena_lib"
path = "src/lib.rs"

[[bin]]
name = "athena"
path = "src/main.rs"

[dependencies]
# calcu-rs = { git = "https://github.com/dlamei/Calcu-rs" }
calcu-rs = { path="backend/Calcu-rs" }
codespan-reporting = "0.11.1"
derive_more = "0.99.17"
itertools = "0.12.0"
logos = "0.13.0"
wasm-bindgen = "0.2.89"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rustyline = "14.0.0"


[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
	'CssStyleDeclaration',
  'Node',
  'Window',
]
