[target.'cfg(not(target_arch = "wasm32"))']
# rustflags = ["-C", "target-feature=sse,sse3,ssse3,+avx"]

# For the wasm32-unknown-unknown target:
[target.'cfg(target_arch = "wasm32")']
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

